### ISSUE TITLE
Integration zabbix otrs

### ISSUE THREAD

**Issue by marlonrib** [Iakim/Zabbix-OTRS#2]
Hello, I'm getting the error below when inserting Action in Zabbix for create.

![2020-02-19 13_38_52_ Dashboard](https://user-images.githubusercontent.com/32168992/74854159-b4c22200-531d-11ea-9fb3-c260d141051b.png)

However, by running the same command directly on the server, the ticket is created. Can you help, please?
![2020-02-19 13_44_49-_zabbix_alertscripts](https://user-images.githubusercontent.com/32168992/74854517-344ff100-531e-11ea-947f-71ce0c4b6cc7.png)

**Comment by Iakim** [comment]
Hello, show me your script in zabbix action.

**Comment by Iakim** [comment]
Pode falar em português! kkkkkkk

**Comment by marlonrib** [comment]
Pode deixar! kkkkk

Segue o script que esta no action no zabbix.

########
/bin/python /usr/lib/zabbix/alertscripts/criar_chamado_zabbix.py --otrs 10.111.160.150 --webservice ZabbixOTRS --user otrs.isaac --pass pass.isaac --customer rnp --title "PROBLEM: {TRIGGER.SEVERITY} - {TRIGGER.NAME} - {TRIGGER.STATUS}" --desc "The host below is having problems.
Name of host: {HOST.HOST}
Name of item: {ITEM.NAME}
Name of trigger: {TRIGGER.NAME}
Status of trigger: {TRIGGER.STATUS}
Severity of trigger: {TRIGGER.SEVERITY}
Event date: {EVENT.DATE} {EVENT.TIME}
Actual date: {DATE} {TIME}
Trigger ID: {TRIGGER.ID}
Event ID: {EVENT.ID}
Total time of event: {EVENT.AGE}" --queue "Zabbix" --service "web" --sla "teste" --triggerid {TRIGGER.ID} --host {HOST.NAME} --status Incident --eventid {EVENT.ID}

![2020-02-27 16_06_49-globalweb_ Configuration of actions](https://user-images.githubusercontent.com/32168992/75477539-3dbf0600-597b-11ea-984b-360b22c00065.png)

**Comment by Iakim** [comment]
Você criou no otrs os mesmos parâmetros para:
--user otrs.isaac
--pass pass.isaac

Se não, vai precisar mudar para o seu usuário e senha do OTRS.

**Comment by Iakim** [comment]
Cara, não faço ideia do que seja, os scripts e a integração está funcionando, teria que debugar, habilita o modo debug no zaabix e pega o log de ação e me manda aqui.

**Comment by Iakim** [comment]
@marlonrib consegue me mandar esse log? Qual a versão do seu zabbix?

**Comment by marlonrib** [comment]
Opa desculpa a demora, estou coletando os logs, assim que terminar te envio. 
A versão dos meu zabbix server é 4.2.6

**Comment by marlonrib** [comment]
Só um detalhe, estou rodando o zabbix-server e o OTRS 6 em containers (docker).

**Comment by marlonrib** [comment]
@Iakim consegui corrigir o problema, conforme o print abaixo. O zabbix estava mandado dois nomes dentro da palavra chave “HOST.NAME”, o que estava causando com que ele interpretasse parte do HOST.NAME como um parâmetro do comando. 

Conforme abaixo inserir as aspas duplas e com isso o problema foi resolvido. 

![2020-03-02 15_48_49-globalweb_ Configuration of actions](https://user-images.githubusercontent.com/32168992/75707342-7cb3cb00-5c9d-11ea-92bd-edf2bf4adbb7.png)

Segue abaixo o erro ocorrido na execução da ação do zabbix.

![2020-03-02 16_03_21-LAB MILTON - root@bglovxts06_ _var_log - Xshell 6 (Free for Home_School)](https://user-images.githubusercontent.com/32168992/75708387-7a527080-5c9f-11ea-8a72-54e1e90320a3.png)

**Comment by Iakim** [comment]
Show!! Fica a dica aí entao de usar tudo com aspas duplas! Vou mudar isso lá no código! Obrigado por compartilhar a sua solução, isso poderá ajudar mais pessoas rapidamente!
